import { hashJson, type DesignIR, type IdentitySpec } from '@pwb/domain';
import type { RasterJob, RasterProvider } from '@pwb/providers';
import type { ImagePromptPlan } from './contracts.js';

export type IdentityAsset = DesignIR['assets']['items'][number];

/** The one raster source the product uses; a direction that does not admit it is never generated. */
export const RASTER_SOURCE = 'higgsfield';

export function admitsGeneratedImagery(identity: IdentitySpec): boolean {
  return identity.imagery.allowedSources.some((source) => source.trim().toLowerCase().startsWith(RASTER_SOURCE));
}

export interface RasterGenerationOptions {
  provider: RasterProvider;
  identityVersionId: string;
  /** The approved contract, whose `imagery.allowedSources` decides whether anything may be generated at all. */
  identity: IdentitySpec;
  model?: string;
  signal?: AbortSignal;
  date?: string;
}

/**
 * Only the approved direction is generated, and only when its own contract
 * admits the raster source. Every asset carries the prompt, the
 * model, the licence the provider returned and the identity version it belongs
 * to, so nothing enters the ledger whose origin cannot be stated. A provider
 * that is not configured still yields a provenance-marked placeholder rather
 * than a silent gap, and no credential is read, logged or stored anywhere here.
 */
export async function generateApprovedImagery(plan: ImagePromptPlan, options: RasterGenerationOptions): Promise<{ assets: IdentityAsset[]; jobs: RasterJob[] }> {
  const model = options.model ?? RASTER_SOURCE;
  const date = options.date ?? new Date().toISOString().slice(0, 10);
  const assets: IdentityAsset[] = [];
  const jobs: RasterJob[] = [];
  if (!admitsGeneratedImagery(options.identity)) return { assets, jobs };
  for (const item of plan.plans) {
    const digest = hashJson({ identityVersionId: options.identityVersionId, directionId: plan.directionId, id: item.id, prompt: item.prompt, negatives: item.negatives, aspect: item.aspect, model });
    const job = await options.provider.submit({ id: `${plan.directionId}-${item.id}`, digest, prompt: item.prompt, model, aspect: item.aspect, identityVersionId: options.identityVersionId }, options.signal);
    jobs.push(job);
    assets.push({
      id: `asset-${plan.directionId}-${item.id}`,
      kind: 'raster',
      uri: job.uri ?? `placeholder:${digest.slice(0, 12)}`,
      alt: item.alt,
      provenance: {
        source: job.status === 'not_configured' ? 'higgsfield-mcp (not configured)' : 'higgsfield-mcp',
        author: 'higgsfield',
        license: job.provenance.license,
        date,
        hash: digest,
        prompt: item.prompt,
        model: job.provenance.model,
        termsNote: `${job.provenance.termsNote} Negatives: ${item.negatives.join('; ')}. Axis: ${item.axis}. Expected licence: ${item.licenceExpectation}.`,
      },
      status: job.status === 'succeeded' ? 'ready' : job.status === 'failed' ? 'failed' : 'placeholder',
    });
  }
  return { assets, jobs };
}

/** A plan is only usable when it respects the direction's own imagery policy. */
export function imageryPolicyViolations(plan: ImagePromptPlan, ir: DesignIR): string[] {
  const violations: string[] = [];
  const photographyRefused = ir.identity.direction.divergence?.matrix.find((vector) => vector.directionId === plan.directionId)?.axes.imagery.key === 'no-photography';
  const generationAllowed = admitsGeneratedImagery(ir.identity);
  for (const item of plan.plans) {
    if (!generationAllowed) {
      violations.push(`Plan ${item.id} would be generated by ${RASTER_SOURCE}, which this direction's allowed sources (${ir.identity.imagery.allowedSources.join(', ')}) do not admit.`);
    }
    if (photographyRefused && (item.role === 'hero' || item.role === 'portrait')) {
      violations.push(`Plan ${item.id} asks for a ${item.role} image, but this direction declares the imagery axis no-photography.`);
    }
    if (!item.licenceExpectation.trim()) violations.push(`Plan ${item.id} states no licence expectation.`);
    const forbidden = [...ir.identity.forbiddenDefaults.motifs, ...ir.identity.forbiddenDefaults.palettes]
      .find((entry) => item.prompt.toLowerCase().includes(entry.toLowerCase()));
    if (forbidden) violations.push(`Plan ${item.id} asks for a forbidden default: ${forbidden}.`);
  }
  return violations;
}
